export const CHANGE_PLAY_LIST_CLASSIFY = 'playList/CHANGE_PLAY_LIST_CLASSIFY'
export const CHANGE_CURRENT_CLASSIFY = 'playList/CHANGE_CURRENT_CLASSIFY'
export const CHANGE_CLASSIFY_SONGS = 'playList/CHANGE_CLASSIFY_SONGS'