export const CHANGE_HOT_ANCHOR = 'diRadio/CHANGE_HOT_ANCHOR'
export const CHANGE_ALL_RADIO_CLASSIFY = 'diRadio/CHANGE_ALL_RADIO_CLASSIFY'
export const CHANGE_HOT_RADIO_RANKS = 'diRadio/CHANGE_HOT_RADIO_RANKS'
export const CHANGE_PROGRAM_RANKS = 'diRadio/CHANGE_PROGRAM_RANKS'
export const CHANGE_TYPE_RECOMMEND_STORY = 'diRadio/CHANGE_TYPE_RECOMMEND_STORY'
export const CHANGE_TYPE_RECOMMEND_SLEEPING =
  'diRadio/CHANGE_TYPE_RECOMMEND_SLEEPING'
export const CHANGE_TYPE_RECOMMEND_TALKING =
  'diRadio/CHANGE_TYPE_RECOMMEND_TALKING'
export const CHANGE_TYPE_RECOMMEND_EMOTIONAL =
  'diRadio/CHANGE_TYPE_RECOMMEND_EMOTIONAL'
export const CHANGE_TYPE_RECOMMEND_COVER = 'diRadio/CHANGE_TYPE_RECOMMEND_COVER'
export const CHANGE_TYPE_RECOMMEND_OTHER = 'diRadio/CHANGE_TYPE_RECOMMEND_OTHER'
