export const CHANGE_HOT_ANCHOR = 'diRadio/CHANGE_HOT_ANCHOR'
export const CHANGE_ALL_RADIO_CLASSIFY = 'diRadio/CHANGE_ALL_RADIO_CLASSIFY'
export const CHANGE_HOT_RADIO_RANKS = 'diRadio/CHANGE_HOT_RADIO_RANKS'
